### ISSUE TITLE
fuzzel support ?

### ISSUE THREAD

**Issue by foxjaw** [kenshaw/wofimoji#2]
Can you add fuzzel support ? Or make another project with fuzzel support ?

**Comment by kenshaw** [comment]
@foxjaw I put in the ability to use any command-line based application. I'm not a user of `fuzzel`, but I'll look at it when I'm able to. Unfortunately, I'm quite busy for the next couple weeks due to family obligations over the Christmas and New Years holidays.

**Comment by kenshaw** [comment]
@foxjaw apologies -- I forgot about this, you can already use wofimoji like the following with `fuzzel`:

```sh
wofimoji --selector='fuzzel' --selector-args='-d'
```

Good luck!
