### ISSUE TITLE
[DOCS(typo)] Wrong install instructions via Go 

### ISSUE THREAD

**Issue by javalsai** [kenshaw/wofimoji#3]
According to the docs, the install command is:
![image](https://github.com/kenshaw/wofimoji/assets/80113062/08ff5e53-a917-4a25-9a77-4c43f0aeb201)

But I think the proper command actually is:
![image](https://github.com/kenshaw/wofimoji/assets/80113062/55e5db7d-5441-423c-9d63-942192059588)

**Comment by kenshaw** [comment]
Apologies, this was mass copy/paste/replace error.
